configure: Append `-lanl` lib to fix missing `getaddrinfo_a()`
Compiling on GNU CC version 8.5.0 20210514 (Red Hat 8.5.0-26) with
glibc version 2.28 throws this error:

  undefined reference to `getaddrinfo_a'

As such, `getaddrinfo_a()` is never used in that environment eventhough
it's available. Append `-lanl` if on `getaddrinfo_a()` check.

Signed-off-by: Alviro Iskandar Setiawan <alviro.iskandar@gnuweeb.org>