log: Fix missing `gettid()` syscall on older glibc version
Compiling on GNU CC version 8.5.0 20210514 (Red Hat 8.5.0-26) with
glibc version 2.28 throws this error:

  src/gwproxy/log.c: In function ‘__pr_log’:
  src/gwproxy/log.c:51:56: warning: implicit declaration of function ‘gettid’; \
                                    did you mean ‘getgid’? [-Wimplicit-function-declaration]
    fprintf(handle, "[%s][%s][%08d]: %s\n", time_buf, ls, gettid(), pb);
                                                          ^~~~~~
                                                          getgid
  src/gwproxy/log.c:51: undefined reference to `gettid'
  collect2: error: ld returned 1 exit status

Fix it by defining our own `__sys_gettid()`.

Signed-off-by: Alviro Iskandar Setiawan <alviro.iskandar@gnuweeb.org>