ci: Downgrade Ubuntu version from 24.04 to 22.04 to fix an LLVM issue
Today, the GitHub CI suddently got hit by LLVM installation errors:

  Package clang-23 is not available, but is referred to by another package.
  This may mean that the package is missing, has been obsoleted, or
  is only available from another source

  Package clangd-23 is not available, but is referred to by another package.
  This may mean that the package is missing, has been obsoleted, or
  is only available from another source

  Package lld-23 is not available, but is referred to by another package.
  This may mean that the package is missing, has been obsoleted, or
  is only available from another source

  Package lldb-23 is not available, but is referred to by another package.
  This may mean that the package is missing, has been obsoleted, or
  is only available from another source

  E: Package 'clang-23' has no installation candidate
  E: Package 'lldb-23' has no installation candidate
  E: Package 'lld-23' has no installation candidate
  E: Package 'clangd-23' has no installation candidate
  Error: Process completed with exit code 100.

We are not sure what is going on, but downgrading the Ubuntu version to
22.04 (jammy) fixes the issue. The installation errors seem to only
happen on Ubuntu 24.04 (noble).

Downgrade to Ubuntu 22.04 (jammy) for now. GCC and Clang still work
just fine on jammy. There is no significant difference for this CI
workflow.

Signed-off-by: Alviro Iskandar Setiawan <alviro.iskandar@gnuweeb.org>